-- Evaluation vocabulary seed. Generated from data/seed/evaluation-vocabulary.tsv.
-- Idempotent: re-running on a populated DB updates classification/notes for
-- existing words and inserts new ones.

INSERT INTO evaluation_vocabulary (word, classification, notes) VALUES
  ('github', 'tech'::vocabulary_classification, NULL),
  ('gitlab', 'tech'::vocabulary_classification, NULL),
  ('bitbucket', 'tech'::vocabulary_classification, NULL),
  ('gitea', 'tech'::vocabulary_classification, NULL),
  ('aws', 'tech'::vocabulary_classification, NULL),
  ('gcp', 'tech'::vocabulary_classification, NULL),
  ('azure', 'tech'::vocabulary_classification, NULL),
  ('cloudflare', 'tech'::vocabulary_classification, NULL),
  ('vercel', 'tech'::vocabulary_classification, NULL),
  ('netlify', 'tech'::vocabulary_classification, NULL),
  ('heroku', 'tech'::vocabulary_classification, NULL),
  ('supabase', 'tech'::vocabulary_classification, NULL),
  ('firebase', 'tech'::vocabulary_classification, NULL),
  ('firestore', 'tech'::vocabulary_classification, NULL),
  ('dynamodb', 'tech'::vocabulary_classification, NULL),
  ('postgres', 'tech'::vocabulary_classification, NULL),
  ('postgresql', 'tech'::vocabulary_classification, NULL),
  ('mysql', 'tech'::vocabulary_classification, NULL),
  ('mariadb', 'tech'::vocabulary_classification, NULL),
  ('mongodb', 'tech'::vocabulary_classification, NULL),
  ('redis', 'tech'::vocabulary_classification, NULL),
  ('sqlite', 'tech'::vocabulary_classification, NULL),
  ('cassandra', 'tech'::vocabulary_classification, NULL),
  ('neo4j', 'tech'::vocabulary_classification, NULL),
  ('cockroachdb', 'tech'::vocabulary_classification, NULL),
  ('docker', 'tech'::vocabulary_classification, NULL),
  ('kubernetes', 'tech'::vocabulary_classification, NULL),
  ('k8s', 'tech'::vocabulary_classification, NULL),
  ('podman', 'tech'::vocabulary_classification, NULL),
  ('helm', 'tech'::vocabulary_classification, NULL),
  ('nomad', 'tech'::vocabulary_classification, NULL),
  ('nextjs', 'tech'::vocabulary_classification, NULL),
  ('nuxt', 'tech'::vocabulary_classification, NULL),
  ('nuxtjs', 'tech'::vocabulary_classification, NULL),
  ('sveltekit', 'tech'::vocabulary_classification, NULL),
  ('astro', 'tech'::vocabulary_classification, NULL),
  ('qwik', 'tech'::vocabulary_classification, NULL),
  ('solidjs', 'tech'::vocabulary_classification, NULL),
  ('remix', 'tech'::vocabulary_classification, NULL),
  ('tanstack', 'tech'::vocabulary_classification, NULL),
  ('gatsby', 'tech'::vocabulary_classification, NULL),
  ('reactjs', 'tech'::vocabulary_classification, NULL),
  ('vuejs', 'tech'::vocabulary_classification, NULL),
  ('angularjs', 'tech'::vocabulary_classification, NULL),
  ('emberjs', 'tech'::vocabulary_classification, NULL),
  ('svelte', 'tech'::vocabulary_classification, NULL),
  ('kotlin', 'tech'::vocabulary_classification, NULL),
  ('rust', 'tech'::vocabulary_classification, NULL),
  ('golang', 'tech'::vocabulary_classification, NULL),
  ('typescript', 'tech'::vocabulary_classification, NULL),
  ('javascript', 'tech'::vocabulary_classification, NULL),
  ('jetpack', 'tech'::vocabulary_classification, NULL),
  ('compose', 'tech'::vocabulary_classification, NULL),
  ('flutter', 'tech'::vocabulary_classification, NULL),
  ('dart', 'tech'::vocabulary_classification, NULL),
  ('swiftui', 'tech'::vocabulary_classification, NULL),
  ('xamarin', 'tech'::vocabulary_classification, NULL),
  ('ionic', 'tech'::vocabulary_classification, NULL),
  ('cordova', 'tech'::vocabulary_classification, NULL),
  ('webpack', 'tech'::vocabulary_classification, NULL),
  ('vite', 'tech'::vocabulary_classification, NULL),
  ('rollup', 'tech'::vocabulary_classification, NULL),
  ('parcel', 'tech'::vocabulary_classification, NULL),
  ('esbuild', 'tech'::vocabulary_classification, NULL),
  ('turbopack', 'tech'::vocabulary_classification, NULL),
  ('gradle', 'tech'::vocabulary_classification, NULL),
  ('maven', 'tech'::vocabulary_classification, NULL),
  ('npm', 'tech'::vocabulary_classification, NULL),
  ('pnpm', 'tech'::vocabulary_classification, NULL),
  ('yarn', 'tech'::vocabulary_classification, NULL),
  ('bun', 'tech'::vocabulary_classification, NULL),
  ('bunx', 'tech'::vocabulary_classification, NULL),
  ('pnpx', 'tech'::vocabulary_classification, NULL),
  ('npx', 'tech'::vocabulary_classification, NULL),
  ('nodejs', 'tech'::vocabulary_classification, NULL),
  ('figma', 'tech'::vocabulary_classification, NULL),
  ('canva', 'tech'::vocabulary_classification, NULL),
  ('miro', 'tech'::vocabulary_classification, NULL),
  ('jest', 'tech'::vocabulary_classification, NULL),
  ('vitest', 'tech'::vocabulary_classification, NULL),
  ('cypress', 'tech'::vocabulary_classification, NULL),
  ('playwright', 'tech'::vocabulary_classification, NULL),
  ('mocha', 'tech'::vocabulary_classification, NULL),
  ('chai', 'tech'::vocabulary_classification, NULL),
  ('selenium', 'tech'::vocabulary_classification, NULL),
  ('drizzle', 'tech'::vocabulary_classification, NULL),
  ('prisma', 'tech'::vocabulary_classification, NULL),
  ('sequelize', 'tech'::vocabulary_classification, NULL),
  ('typeorm', 'tech'::vocabulary_classification, NULL),
  ('mongoose', 'tech'::vocabulary_classification, NULL),
  ('graphql', 'tech'::vocabulary_classification, NULL),
  ('restful', 'tech'::vocabulary_classification, NULL),
  ('grpc', 'tech'::vocabulary_classification, NULL),
  ('websocket', 'tech'::vocabulary_classification, NULL),
  ('webrtc', 'tech'::vocabulary_classification, NULL),
  ('tailwindcss', 'tech'::vocabulary_classification, NULL),
  ('tailwind', 'tech'::vocabulary_classification, NULL),
  ('bootstrap', 'tech'::vocabulary_classification, NULL),
  ('chakraui', 'tech'::vocabulary_classification, NULL),
  ('shadcn', 'tech'::vocabulary_classification, NULL),
  ('radix', 'tech'::vocabulary_classification, NULL),
  ('headlessui', 'tech'::vocabulary_classification, NULL),
  ('redux', 'tech'::vocabulary_classification, NULL),
  ('mobx', 'tech'::vocabulary_classification, NULL),
  ('zustand', 'tech'::vocabulary_classification, NULL),
  ('recoil', 'tech'::vocabulary_classification, NULL),
  ('jotai', 'tech'::vocabulary_classification, NULL),
  ('pinia', 'tech'::vocabulary_classification, NULL),
  ('vuex', 'tech'::vocabulary_classification, NULL),
  ('effect', 'tech'::vocabulary_classification, NULL),
  ('fpts', 'tech'::vocabulary_classification, NULL),
  ('api', 'tech'::vocabulary_classification, NULL),
  ('sdk', 'tech'::vocabulary_classification, NULL),
  ('cli', 'tech'::vocabulary_classification, NULL),
  ('gui', 'tech'::vocabulary_classification, NULL),
  ('url', 'tech'::vocabulary_classification, NULL),
  ('uri', 'tech'::vocabulary_classification, NULL),
  ('http', 'tech'::vocabulary_classification, NULL),
  ('https', 'tech'::vocabulary_classification, NULL),
  ('json', 'tech'::vocabulary_classification, NULL),
  ('xml', 'tech'::vocabulary_classification, NULL),
  ('yaml', 'tech'::vocabulary_classification, NULL),
  ('toml', 'tech'::vocabulary_classification, NULL),
  ('csv', 'tech'::vocabulary_classification, NULL),
  ('sql', 'tech'::vocabulary_classification, NULL),
  ('nosql', 'tech'::vocabulary_classification, NULL),
  ('orm', 'tech'::vocabulary_classification, NULL),
  ('jwt', 'tech'::vocabulary_classification, NULL),
  ('oauth', 'tech'::vocabulary_classification, NULL),
  ('saml', 'tech'::vocabulary_classification, NULL),
  ('ldap', 'tech'::vocabulary_classification, NULL),
  ('ssl', 'tech'::vocabulary_classification, NULL),
  ('tls', 'tech'::vocabulary_classification, NULL),
  ('dns', 'tech'::vocabulary_classification, NULL),
  ('dhcp', 'tech'::vocabulary_classification, NULL),
  ('tcp', 'tech'::vocabulary_classification, NULL),
  ('udp', 'tech'::vocabulary_classification, NULL),
  ('ip', 'tech'::vocabulary_classification, NULL),
  ('mac', 'tech'::vocabulary_classification, NULL),
  ('nat', 'tech'::vocabulary_classification, NULL),
  ('vpn', 'tech'::vocabulary_classification, NULL),
  ('pwa', 'tech'::vocabulary_classification, NULL),
  ('spa', 'tech'::vocabulary_classification, NULL),
  ('ssr', 'tech'::vocabulary_classification, NULL),
  ('ssg', 'tech'::vocabulary_classification, NULL),
  ('csr', 'tech'::vocabulary_classification, NULL),
  ('isr', 'tech'::vocabulary_classification, NULL),
  ('mpa', 'tech'::vocabulary_classification, NULL),
  ('mvc', 'tech'::vocabulary_classification, NULL),
  ('mvp', 'tech'::vocabulary_classification, NULL),
  ('mvvm', 'tech'::vocabulary_classification, NULL),
  ('ide', 'tech'::vocabulary_classification, NULL),
  ('vscode', 'tech'::vocabulary_classification, NULL),
  ('intellij', 'tech'::vocabulary_classification, NULL),
  ('webstorm', 'tech'::vocabulary_classification, NULL),
  ('pycharm', 'tech'::vocabulary_classification, NULL),
  ('phpstorm', 'tech'::vocabulary_classification, NULL),
  ('ios', 'tech'::vocabulary_classification, NULL),
  ('macos', 'tech'::vocabulary_classification, NULL),
  ('ipados', 'tech'::vocabulary_classification, NULL),
  ('watchos', 'tech'::vocabulary_classification, NULL),
  ('tvos', 'tech'::vocabulary_classification, NULL),
  ('devops', 'tech'::vocabulary_classification, NULL),
  ('ci', 'tech'::vocabulary_classification, NULL),
  ('cd', 'tech'::vocabulary_classification, NULL),
  ('saas', 'tech'::vocabulary_classification, NULL),
  ('paas', 'tech'::vocabulary_classification, NULL),
  ('iaas', 'tech'::vocabulary_classification, NULL),
  ('baas', 'tech'::vocabulary_classification, NULL),
  ('faas', 'tech'::vocabulary_classification, NULL),
  ('hlm', 'ignore'::vocabulary_classification, 'common Indonesian abbreviation for "halaman"'),
  ('hal', 'ignore'::vocabulary_classification, '"halaman" abbreviation'),
  ('tgl', 'ignore'::vocabulary_classification, '"tanggal" abbreviation'),
  ('thn', 'ignore'::vocabulary_classification, '"tahun" abbreviation'),
  ('dsb', 'ignore'::vocabulary_classification, '"dan sebagainya"'),
  ('dll', 'ignore'::vocabulary_classification, '"dan lain-lain"'),
  ('dst', 'ignore'::vocabulary_classification, '"dan seterusnya"'),
  ('yg', 'ignore'::vocabulary_classification, '"yang" abbreviation'),
  ('dgn', 'ignore'::vocabulary_classification, '"dengan" abbreviation'),
  ('dr', 'ignore'::vocabulary_classification, '"dari" abbreviation'),
  ('no', 'ignore'::vocabulary_classification, '"nomor" abbreviation'),
  ('vol', 'ignore'::vocabulary_classification, '"volume" abbreviation'),
  ('ed', 'ignore'::vocabulary_classification, '"edisi" abbreviation'),
  ('jl', 'ignore'::vocabulary_classification, '"jalan" abbreviation')
ON CONFLICT (word) DO UPDATE SET
  classification = EXCLUDED.classification,
  notes = EXCLUDED.notes,
  updated_at = now();
