/**
 * Build per-source KBBI SQL dumps and the merged core_kbbi.sql seed.
 *
 * Managed sources (fetched from GitHub raw URLs, converted to PG SQL):
 *   - damzaky/kumpulan-kata-bahasa-indonesia-KBBI   plain text -> dictionary_lemma
 *   - aryakdaniswara/kbbi-dataset-kbbi-v             CSV        -> dictionary
 *
 * Unmanaged but included in core:
 *   - deploy/seed/kbbi/source/dyazincahya_kbbi_sql_database.sql   (existing)
 *   - deploy/seed/kbbi/source/shulhan_hunspell_id.sql             (existing)
 *
 * Skipped (would duplicate the above):
 *   - bachors/KBBI.sql                  byte-identical to dyazincahya
 *   - baguskto/kbbi-api/kbbi-dataset-*  vendored copy of aryakdaniswara
 *
 * Run: bun .claude/scripts/build-kbbi-sources.ts [--force]
 *   --force re-fetches and overwrites managed source files even if present.
 *
 * Output:
 *   deploy/seed/kbbi/source/USER_REPO_kbbi*.sql   per-source dumps
 *   deploy/seed/kbbi/core_kbbi.sql                TRUNCATE-then-INSERT merge
 */

const KBBI_DIR = 'deploy/seed/kbbi'
const SOURCE_DIR = KBBI_DIR + '/source'
const CORE_OUT = KBBI_DIR + '/core_kbbi.sql'

const LEMMA_RE = /^[a-zà-ÿ]+(?:-[a-zà-ÿ]+)?$/

const FORCE = process.argv.includes('--force')

type ManagedSource = {
  outFile: string
  sourceTag: string
  build: () => Promise<{ sql: string; rows: number }>
}

const escape = (s: string): string => s.replace(/'/g, "''")

const chunked = <T>(arr: T[], size: number): T[][] => {
  const out: T[][] = []
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size))
  return out
}

const fetchText = async (url: string): Promise<string> => {
  console.log('  fetch ' + url)
  const res = await fetch(url)
  if (!res.ok) throw new Error('fetch failed: ' + String(res.status))
  return res.text()
}

const buildLemmaSql = (
  words: string[],
  sourceTag: string,
  origin: string,
): string => {
  const headerLines = [
    '-- KBBI lemma supplement -- source: ' + sourceTag,
    '-- Generated by .claude/scripts/build-kbbi-sources.ts from ' + origin + '.',
    '-- Idempotent: ON CONFLICT (word) DO NOTHING. Table: dictionary_lemma.',
    '-- Words: ' + String(words.length),
    '',
    '',
  ]
  const out: string[] = [headerLines.join('\n')]
  for (const batch of chunked(words, 1000)) {
    const tuples = batch.map((w) => "('" + escape(w) + "', '" + sourceTag + "')")
    const values = tuples.join(',\n  ')
    out.push(
      'INSERT INTO public."dictionary_lemma" (word, source) VALUES\n  ' +
        values +
        '\nON CONFLICT (word) DO NOTHING;\n',
    )
  }
  return out.join('\n')
}

const buildDictionarySql = (
  rows: Array<{ word: string; arti: string }>,
  sourceTag: string,
  origin: string,
): string => {
  const headerLines = [
    '-- KBBI rich dictionary -- source: ' + sourceTag,
    '-- Generated by .claude/scripts/build-kbbi-sources.ts from ' + origin + '.',
    '-- Loaded as part of core_kbbi.sql after TRUNCATE; safe to re-run as part of the bundle.',
    '-- The dictionary table has no UNIQUE constraint (homonyms are intentional), so this file',
    '-- has no ON CONFLICT clause - running it standalone twice will produce duplicates.',
    '-- Rows: ' + String(rows.length),
    '',
    '',
  ]
  const out: string[] = [headerLines.join('\n')]
  for (const batch of chunked(rows, 500)) {
    const tuples = batch.map(
      (r) =>
        "('" +
        escape(r.word) +
        "', '" +
        escape(r.arti) +
        "', 1, '" +
        sourceTag +
        "')",
    )
    const values = tuples.join(',\n  ')
    out.push(
      'INSERT INTO public."dictionary" (word, arti, "type", source) VALUES\n  ' +
        values +
        ';\n',
    )
  }
  return out.join('\n')
}

// --- damzaky: plain-text wordlist -> dictionary_lemma ---
const buildDamzaky = async (): Promise<{ sql: string; rows: number }> => {
  const url =
    'https://raw.githubusercontent.com/damzaky/kumpulan-kata-bahasa-indonesia-KBBI/HEAD/list_1.0.0.txt'
  const raw = await fetchText(url)
  const set = new Set<string>()
  for (const line of raw.split('\n')) {
    const w = line.trim().toLowerCase()
    if (!w) continue
    if (!LEMMA_RE.test(w)) continue
    set.add(w)
  }
  const words = [...set].toSorted()
  const sqlText = buildLemmaSql(
    words,
    'kbbi-damzaky',
    'damzaky/kumpulan-kata-bahasa-indonesia-KBBI (list_1.0.0.txt, KBBI v6.1.0)',
  )
  return { sql: sqlText, rows: words.length }
}

// Minimal RFC 4180 line parser. Handles "" escape and ,-separated cells.
// Does NOT handle newlines inside quoted cells -- fine for the aryakdaniswara
// CSV (verified by sampling: no embedded newlines in submakna).
const parseCsvLine = (line: string): string[] => {
  const cells: string[] = []
  let cell = ''
  let inQuotes = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i]
    if (inQuotes) {
      if (c === '"') {
        if (line[i + 1] === '"') {
          cell += '"'
          i++
        } else {
          inQuotes = false
        }
      } else {
        cell += c
      }
    } else if (c === ',') {
      cells.push(cell)
      cell = ''
    } else if (c === '"' && cell === '') {
      inQuotes = true
    } else {
      cell += c
    }
  }
  cells.push(cell)
  return cells
}

// --- aryakdaniswara: rich CSV -> dictionary ---
const buildAryakdaniswara = async (): Promise<{ sql: string; rows: number }> => {
  const url =
    'https://raw.githubusercontent.com/aryakdaniswara/kbbi-dataset-kbbi-v/HEAD/csv/kbbi_v.csv'
  const raw = await fetchText(url)
  const lines = raw.split('\n')
  const headerCells = parseCsvLine(lines[0])
  // `key` is the plain lemma (e.g. "abadi"); `nama` is the syllable-broken
  // form ("a.ba.di") so we ignore it. `submakna` holds the gloss.
  const idxKey = headerCells.indexOf('key')
  const idxSubmakna = headerCells.indexOf('submakna')
  if (idxKey < 0 || idxSubmakna < 0) {
    throw new Error(
      'aryakdaniswara CSV missing expected columns; got ' + headerCells.join(', '),
    )
  }
  // Dedupe by (word, submakna) -- the CSV has homonym rows we want to preserve
  // (multiple submakna per lemma is legitimate) but exact dupes we drop.
  const seen = new Set<string>()
  const rows: Array<{ word: string; arti: string }> = []
  let skipped = 0
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i]
    if (!line) continue
    const cells = parseCsvLine(line)
    if (cells.length <= idxSubmakna) {
      skipped++
      continue
    }
    const word = (cells[idxKey] ?? '').trim().toLowerCase()
    const arti = (cells[idxSubmakna] ?? '').trim()
    if (!word || !arti) {
      skipped++
      continue
    }
    // Drop multi-word phrases / proverbs / parenthesised entries -- they bloat
    // the membership set without helping word verification. Keep "anak-anak"-style
    // reduplication.
    if (!LEMMA_RE.test(word)) {
      skipped++
      continue
    }
    const dedupeKey = word + '\t' + arti
    if (seen.has(dedupeKey)) continue
    seen.add(dedupeKey)
    rows.push({ word, arti })
  }
  console.log(
    '  aryakdaniswara: kept ' +
      String(rows.length) +
      ' rows, skipped ' +
      String(skipped) +
      ' (phrases/empty)',
  )
  const sqlText = buildDictionarySql(
    rows,
    'kbbi-aryakdaniswara',
    'aryakdaniswara/kbbi-dataset-kbbi-v (csv/kbbi_v.csv, KBBI V from mobile app)',
  )
  return { sql: sqlText, rows: rows.length }
}

const MANAGED: ManagedSource[] = [
  {
    outFile: SOURCE_DIR + '/damzaky_kumpulan_kata_bahasa_indonesia_kbbi.sql',
    sourceTag: 'kbbi-damzaky',
    build: buildDamzaky,
  },
  {
    outFile: SOURCE_DIR + '/aryakdaniswara_kbbi_dataset_kbbi_v.sql',
    sourceTag: 'kbbi-aryakdaniswara',
    build: buildAryakdaniswara,
  },
]

const buildManaged = async (): Promise<void> => {
  for (const src of MANAGED) {
    const exists = await Bun.file(src.outFile).exists()
    if (exists && !FORCE) {
      console.log('skip ' + src.outFile + ' (exists; pass --force to regenerate)')
      continue
    }
    console.log('build ' + src.outFile)
    const result = await src.build()
    await Bun.write(src.outFile, result.sql)
    const mb = (result.sql.length / 1_048_576).toFixed(2)
    console.log(
      '  wrote ' + src.outFile + ' (' + mb + ' MB, ' + String(result.rows) + ' rows)',
    )
  }
}

// Deterministic order for the merge. Earlier entries take precedence on
// dictionary_lemma (later ON CONFLICT DO NOTHING entries are skipped); for the
// dictionary table the merge concatenates without dedup.
const CORE_ORDER = [
  'dyazincahya_kbbi_sql_database.sql',
  'aryakdaniswara_kbbi_dataset_kbbi_v.sql',
  'shulhan_hunspell_id.sql',
  'damzaky_kumpulan_kata_bahasa_indonesia_kbbi.sql',
]

const buildCore = async (): Promise<void> => {
  console.log('build ' + CORE_OUT)
  const headerLines = [
    '-- core_kbbi.sql -- merged KBBI seed for citetrack.',
    '-- Generated by .claude/scripts/build-kbbi-sources.ts. DO NOT EDIT BY HAND.',
    '-- Re-run that script (and commit) to refresh.',
    '--',
    '-- Composition order (also reflected in deploy/seed/kbbi/source/):',
    ...CORE_ORDER.map((f) => '--   ' + f),
    '--',
    '-- Idempotency: this file TRUNCATEs both target tables before re-INSERTing, so',
    '-- it is safe to run any number of times on an existing database. The dictionary',
    '-- table allows homonym duplicates (no UNIQUE constraint), so the truncate is',
    '-- the only mechanism keeping reloads from accumulating dupes.',
    '',
    '\\set ON_ERROR_STOP on',
    '',
    'BEGIN;',
    'TRUNCATE TABLE public."dictionary" RESTART IDENTITY;',
    'TRUNCATE TABLE public."dictionary_lemma";',
    '',
  ]
  const parts: string[] = [headerLines.join('\n')]
  for (const fname of CORE_ORDER) {
    const path = SOURCE_DIR + '/' + fname
    const exists = await Bun.file(path).exists()
    if (!exists) {
      throw new Error('expected ' + path + ' but it is missing -- run the generator first')
    }
    const bytes = Bun.file(path).size / 1_048_576
    parts.push('\n-- ============================================================')
    parts.push('-- BEGIN ' + fname + ' (' + bytes.toFixed(2) + ' MB)')
    parts.push('-- ============================================================')
    parts.push(await Bun.file(path).text())
    parts.push('-- END ' + fname)
  }
  parts.push('\nCOMMIT;\n')
  const merged = parts.join('\n')
  await Bun.write(CORE_OUT, merged)
  const mb = (merged.length / 1_048_576).toFixed(2)
  console.log('  wrote ' + CORE_OUT + ' (' + mb + ' MB)')
}

const main = async (): Promise<void> => {
  await buildManaged()
  await buildCore()
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
