/**
 * Build a provenance-tagged KBBI lemma supplement from the LGPL-licensed
 * shuLhan/hunspell-id dictionary.
 *
 * Source: https://github.com/shuLhan/hunspell-id (id_ID.dic) — checked against
 * KBBI lemmas, includes modern loanwords (konten, fitur, validasi, ...) that the
 * original dyazincahya/KBBI-SQL dump is missing.
 *
 * Output: deploy/seed/kbbi-lemma-supplement.sql — idempotent INSERTs into the
 * dictionary_lemma membership table, tagged source='hunspell-id-shulhan'.
 *
 * Run: bun .claude/scripts/build-kbbi-supplement.ts
 */
import { sql } from 'drizzle-orm'
import { db } from '#/db'

const DIC_URL = 'https://raw.githubusercontent.com/shuLhan/hunspell-id/main/id_ID.dic'
const SOURCE = 'hunspell-id-shulhan'
const OUT = 'deploy/seed/kbbi-lemma-supplement.sql'

// Keep lemmas only: lowercase Indonesian letters, optional single internal
// hyphen (reduplication like "anak-anak"). Drop affix lines (-an, meng-),
// anything with digits, uppercase (proper nouns), or stray punctuation.
const LEMMA_RE = /^[a-zà-ÿ]+(?:-[a-zà-ÿ]+)?$/

const parseDic = (raw: string): string[] => {
  const lines = raw.split('\n')
  const out = new Set<string>()
  // First line is the declared count — skip it.
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i]
    if (!line) continue
    // Strip Hunspell affix flags ("kelola/D0M0P0PaT0" → "kelola").
    const word = line.split('/')[0].trim().toLowerCase()
    if (!word) continue
    if (word.startsWith('-') || word.endsWith('-')) continue
    if (!LEMMA_RE.test(word)) continue
    out.add(word)
  }
  return [...out].toSorted()
}

const escape = (s: string): string => s.replace(/'/g, "''")

const buildSql = (words: string[]): string => {
  const header = `-- KBBI lemma supplement (membership-only) — source: ${SOURCE}
-- Generated by .claude/scripts/build-kbbi-supplement.ts from shuLhan/hunspell-id (LGPL).
-- Idempotent: safe to re-run. Table created by Drizzle migration (schema: dictionaryLemma).
-- Words: ${words.length}

`
  const chunks: string[] = [header]
  const CHUNK = 1000
  for (let i = 0; i < words.length; i += CHUNK) {
    const batch = words.slice(i, i + CHUNK)
    const values = batch
      .map((w) => `('${escape(w)}', '${SOURCE}')`)
      .join(',\n  ')
    chunks.push(
      `INSERT INTO public."dictionary_lemma" (word, source) VALUES\n  ${values}\nON CONFLICT (word) DO NOTHING;\n`,
    )
  }
  return chunks.join('\n')
}

const main = async (): Promise<void> => {
  console.log(`Fetching ${DIC_URL} ...`)
  const res = await fetch(DIC_URL)
  if (!res.ok) throw new Error(`fetch failed: ${res.status}`)
  const raw = await res.text()

  const lemmas = parseDic(raw)
  console.log(`Parsed ${lemmas.length} hunspell lemmas.`)

  // Diff against the existing dump for the coverage report.
  const dumpRows = await db.execute<{ word: string }>(
    sql`SELECT DISTINCT lower(trim(word)) AS word FROM dictionary`,
  )
  const dump = new Set<string>()
  for (const r of dumpRows.rows ?? dumpRows) {
    const w = (r as { word: string | null }).word
    if (w) dump.add(w)
  }
  const novel = lemmas.filter((w) => !dump.has(w))
  console.log(`Dump words: ${dump.size}`)
  console.log(`Hunspell adds ${novel.length} words NOT already in the dump.`)
  console.log(
    `Sample new words: ${novel.slice(0, 20).join(', ')}`,
  )

  const sqlText = buildSql(lemmas)
  await Bun.write(OUT, sqlText)
  console.log(`Wrote ${OUT} (${(sqlText.length / 1_048_576).toFixed(2)} MB, ${lemmas.length} rows).`)
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
