type PipelinePhase =
  | 'upload'
  | 'parsing-citations'
  | 'review-citations'
  | 'parsing-references'
  | 'review-references'
  | 'matching'
  | 'review-matches'
  | 'upload-sources'
  | 'matching-passages'
  | 'review-passages'
  | 'error'
