/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsJobIdRouteImport } from './routes/results/$jobId'
import { Route as EvaluationEvalIdRouteImport } from './routes/evaluation/$evalId'
import { Route as ApiPdfJobIdRouteImport } from './routes/api/pdf.$jobId'
import { Route as ApiEvaluationPdfEvalIdRouteImport } from './routes/api/evaluation-pdf.$evalId'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsJobIdRoute = ResultsJobIdRouteImport.update({
  id: '/results/$jobId',
  path: '/results/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationEvalIdRoute = EvaluationEvalIdRouteImport.update({
  id: '/$evalId',
  path: '/$evalId',
  getParentRoute: () => EvaluationRoute,
} as any)
const ApiPdfJobIdRoute = ApiPdfJobIdRouteImport.update({
  id: '/api/pdf/$jobId',
  path: '/api/pdf/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationPdfEvalIdRoute = ApiEvaluationPdfEvalIdRouteImport.update({
  id: '/api/evaluation-pdf/$evalId',
  path: '/api/evaluation-pdf/$evalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/track': typeof TrackRoute
  '/evaluation/$evalId': typeof EvaluationEvalIdRoute
  '/results/$jobId': typeof ResultsJobIdRoute
  '/api/evaluation-pdf/$evalId': typeof ApiEvaluationPdfEvalIdRoute
  '/api/pdf/$jobId': typeof ApiPdfJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/track': typeof TrackRoute
  '/evaluation/$evalId': typeof EvaluationEvalIdRoute
  '/results/$jobId': typeof ResultsJobIdRoute
  '/api/evaluation-pdf/$evalId': typeof ApiEvaluationPdfEvalIdRoute
  '/api/pdf/$jobId': typeof ApiPdfJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/track': typeof TrackRoute
  '/evaluation/$evalId': typeof EvaluationEvalIdRoute
  '/results/$jobId': typeof ResultsJobIdRoute
  '/api/evaluation-pdf/$evalId': typeof ApiEvaluationPdfEvalIdRoute
  '/api/pdf/$jobId': typeof ApiPdfJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evaluation'
    | '/track'
    | '/evaluation/$evalId'
    | '/results/$jobId'
    | '/api/evaluation-pdf/$evalId'
    | '/api/pdf/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluation'
    | '/track'
    | '/evaluation/$evalId'
    | '/results/$jobId'
    | '/api/evaluation-pdf/$evalId'
    | '/api/pdf/$jobId'
  id:
    | '__root__'
    | '/'
    | '/evaluation'
    | '/track'
    | '/evaluation/$evalId'
    | '/results/$jobId'
    | '/api/evaluation-pdf/$evalId'
    | '/api/pdf/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationRoute: typeof EvaluationRouteWithChildren
  TrackRoute: typeof TrackRoute
  ResultsJobIdRoute: typeof ResultsJobIdRoute
  ApiEvaluationPdfEvalIdRoute: typeof ApiEvaluationPdfEvalIdRoute
  ApiPdfJobIdRoute: typeof ApiPdfJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$jobId': {
      id: '/results/$jobId'
      path: '/results/$jobId'
      fullPath: '/results/$jobId'
      preLoaderRoute: typeof ResultsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/$evalId': {
      id: '/evaluation/$evalId'
      path: '/$evalId'
      fullPath: '/evaluation/$evalId'
      preLoaderRoute: typeof EvaluationEvalIdRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/api/pdf/$jobId': {
      id: '/api/pdf/$jobId'
      path: '/api/pdf/$jobId'
      fullPath: '/api/pdf/$jobId'
      preLoaderRoute: typeof ApiPdfJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluation-pdf/$evalId': {
      id: '/api/evaluation-pdf/$evalId'
      path: '/api/evaluation-pdf/$evalId'
      fullPath: '/api/evaluation-pdf/$evalId'
      preLoaderRoute: typeof ApiEvaluationPdfEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EvaluationRouteChildren {
  EvaluationEvalIdRoute: typeof EvaluationEvalIdRoute
}

const EvaluationRouteChildren: EvaluationRouteChildren = {
  EvaluationEvalIdRoute: EvaluationEvalIdRoute,
}

const EvaluationRouteWithChildren = EvaluationRoute._addFileChildren(
  EvaluationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationRoute: EvaluationRouteWithChildren,
  TrackRoute: TrackRoute,
  ResultsJobIdRoute: ResultsJobIdRoute,
  ApiEvaluationPdfEvalIdRoute: ApiEvaluationPdfEvalIdRoute,
  ApiPdfJobIdRoute: ApiPdfJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
