/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIndexRouteImport } from './routes/track/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as AdminApiLogsRouteImport } from './routes/admin/api-logs'
import { Route as ResultsJobIdIndexRouteImport } from './routes/results/$jobId/index'
import { Route as EvaluationEvalIdIndexRouteImport } from './routes/evaluation/$evalId/index'
import { Route as ApiPdfJobIdRouteImport } from './routes/api/pdf.$jobId'
import { Route as ApiEvaluationPdfEvalIdRouteImport } from './routes/api/evaluation-pdf.$evalId'
import { Route as ApiEvaluationAnnotatedPdfEvalIdRouteImport } from './routes/api/evaluation-annotated-pdf.$evalId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiLogsRoute = AdminApiLogsRouteImport.update({
  id: '/admin/api-logs',
  path: '/admin/api-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsJobIdIndexRoute = ResultsJobIdIndexRouteImport.update({
  id: '/results/$jobId/',
  path: '/results/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationEvalIdIndexRoute = EvaluationEvalIdIndexRouteImport.update({
  id: '/$evalId/',
  path: '/$evalId/',
  getParentRoute: () => EvaluationRoute,
} as any)
const ApiPdfJobIdRoute = ApiPdfJobIdRouteImport.update({
  id: '/api/pdf/$jobId',
  path: '/api/pdf/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationPdfEvalIdRoute = ApiEvaluationPdfEvalIdRouteImport.update({
  id: '/api/evaluation-pdf/$evalId',
  path: '/api/evaluation-pdf/$evalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationAnnotatedPdfEvalIdRoute =
  ApiEvaluationAnnotatedPdfEvalIdRouteImport.update({
    id: '/api/evaluation-annotated-pdf/$evalId',
    path: '/api/evaluation-annotated-pdf/$evalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/history/': typeof HistoryIndexRoute
  '/track/': typeof TrackIndexRoute
  '/api/evaluation-annotated-pdf/$evalId': typeof ApiEvaluationAnnotatedPdfEvalIdRoute
  '/api/evaluation-pdf/$evalId': typeof ApiEvaluationPdfEvalIdRoute
  '/api/pdf/$jobId': typeof ApiPdfJobIdRoute
  '/evaluation/$evalId/': typeof EvaluationEvalIdIndexRoute
  '/results/$jobId/': typeof ResultsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/history': typeof HistoryIndexRoute
  '/track': typeof TrackIndexRoute
  '/api/evaluation-annotated-pdf/$evalId': typeof ApiEvaluationAnnotatedPdfEvalIdRoute
  '/api/evaluation-pdf/$evalId': typeof ApiEvaluationPdfEvalIdRoute
  '/api/pdf/$jobId': typeof ApiPdfJobIdRoute
  '/evaluation/$evalId': typeof EvaluationEvalIdIndexRoute
  '/results/$jobId': typeof ResultsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/history/': typeof HistoryIndexRoute
  '/track/': typeof TrackIndexRoute
  '/api/evaluation-annotated-pdf/$evalId': typeof ApiEvaluationAnnotatedPdfEvalIdRoute
  '/api/evaluation-pdf/$evalId': typeof ApiEvaluationPdfEvalIdRoute
  '/api/pdf/$jobId': typeof ApiPdfJobIdRoute
  '/evaluation/$evalId/': typeof EvaluationEvalIdIndexRoute
  '/results/$jobId/': typeof ResultsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evaluation'
    | '/privacy'
    | '/settings'
    | '/admin/api-logs'
    | '/history/'
    | '/track/'
    | '/api/evaluation-annotated-pdf/$evalId'
    | '/api/evaluation-pdf/$evalId'
    | '/api/pdf/$jobId'
    | '/evaluation/$evalId/'
    | '/results/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluation'
    | '/privacy'
    | '/settings'
    | '/admin/api-logs'
    | '/history'
    | '/track'
    | '/api/evaluation-annotated-pdf/$evalId'
    | '/api/evaluation-pdf/$evalId'
    | '/api/pdf/$jobId'
    | '/evaluation/$evalId'
    | '/results/$jobId'
  id:
    | '__root__'
    | '/'
    | '/evaluation'
    | '/privacy'
    | '/settings'
    | '/admin/api-logs'
    | '/history/'
    | '/track/'
    | '/api/evaluation-annotated-pdf/$evalId'
    | '/api/evaluation-pdf/$evalId'
    | '/api/pdf/$jobId'
    | '/evaluation/$evalId/'
    | '/results/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationRoute: typeof EvaluationRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  AdminApiLogsRoute: typeof AdminApiLogsRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  TrackIndexRoute: typeof TrackIndexRoute
  ApiEvaluationAnnotatedPdfEvalIdRoute: typeof ApiEvaluationAnnotatedPdfEvalIdRoute
  ApiEvaluationPdfEvalIdRoute: typeof ApiEvaluationPdfEvalIdRoute
  ApiPdfJobIdRoute: typeof ApiPdfJobIdRoute
  ResultsJobIdIndexRoute: typeof ResultsJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api-logs': {
      id: '/admin/api-logs'
      path: '/admin/api-logs'
      fullPath: '/admin/api-logs'
      preLoaderRoute: typeof AdminApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$jobId/': {
      id: '/results/$jobId/'
      path: '/results/$jobId'
      fullPath: '/results/$jobId/'
      preLoaderRoute: typeof ResultsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/$evalId/': {
      id: '/evaluation/$evalId/'
      path: '/$evalId'
      fullPath: '/evaluation/$evalId/'
      preLoaderRoute: typeof EvaluationEvalIdIndexRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/api/pdf/$jobId': {
      id: '/api/pdf/$jobId'
      path: '/api/pdf/$jobId'
      fullPath: '/api/pdf/$jobId'
      preLoaderRoute: typeof ApiPdfJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluation-pdf/$evalId': {
      id: '/api/evaluation-pdf/$evalId'
      path: '/api/evaluation-pdf/$evalId'
      fullPath: '/api/evaluation-pdf/$evalId'
      preLoaderRoute: typeof ApiEvaluationPdfEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluation-annotated-pdf/$evalId': {
      id: '/api/evaluation-annotated-pdf/$evalId'
      path: '/api/evaluation-annotated-pdf/$evalId'
      fullPath: '/api/evaluation-annotated-pdf/$evalId'
      preLoaderRoute: typeof ApiEvaluationAnnotatedPdfEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EvaluationRouteChildren {
  EvaluationEvalIdIndexRoute: typeof EvaluationEvalIdIndexRoute
}

const EvaluationRouteChildren: EvaluationRouteChildren = {
  EvaluationEvalIdIndexRoute: EvaluationEvalIdIndexRoute,
}

const EvaluationRouteWithChildren = EvaluationRoute._addFileChildren(
  EvaluationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationRoute: EvaluationRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  AdminApiLogsRoute: AdminApiLogsRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  TrackIndexRoute: TrackIndexRoute,
  ApiEvaluationAnnotatedPdfEvalIdRoute: ApiEvaluationAnnotatedPdfEvalIdRoute,
  ApiEvaluationPdfEvalIdRoute: ApiEvaluationPdfEvalIdRoute,
  ApiPdfJobIdRoute: ApiPdfJobIdRoute,
  ResultsJobIdIndexRoute: ResultsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
